channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=24.0
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.0
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==6.1.0
  - scikit-learn==1.6.0
  - scipy==1.14.1
name: mlflow-env
